### ISSUE TITLE
spring-data-gremlin-example project in example folder build fails.

### ISSUE THREAD

**Issue by renilJoseph** [Microsoft/spring-data-gremlin#107]
mvn clean install -U 

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Data gremlin - Example 0.0.1.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.microsoft.spring.data.gremlin:spring-data-gremlin:jar:0.0.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.219 s
[INFO] Finished at: 2018-06-12T16:15:27+05:30
[INFO] Final Memory: 16M/39M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project spring-data-gremlin-example: Could not resolve dependencies for project com.microsoft.spring.data.gremlin.examples:spr
ing-data-gremlin-example:jar:0.0.1.BUILD-SNAPSHOT: Could not find artifact com.microsoft.spring.data.gremlin:spring-data-gremlin:jar:0.0.1-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Also i could not find spring-data-gremlin in maven central repository and the following dependency addition fails.

> <dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>spring-data-gremlin</artifactId>
    <version>2.x.x</version>
</dependency>

what is the version as in place of 2.x.x ?

**Comment by Incarnation-p-lee** [comment]
@renilJoseph 
Thanks for having a try on spring-data-gremlin. As we have not release the first version for this repo, you cannot find that package from maven.
If you want to run it locally, you can `git clone` this repo and 
* `mvn clean install`
* replace `2.x.x` to `0.0.1-SNAPSHOT`
* rebuild.

For now we are preparing the release for this repo, you may locate this package before the next Monday if favoring.

**Comment by Incarnation-p-lee** [comment]
@renilJoseph 
Thanks for your time, and We have release the first version [spring-data-gremlin 2.0.0](https://github.com/Microsoft/spring-data-gremlin/releases/tag/v2.0.0). And any comments is welcome, :)
