### ISSUE TITLE
Need for @Graph

### ISSUE THREAD

**Issue by corneil** [microsoft/spring-data-gremlin#121]
Is the Network class needed?
The use of the Network class annotated with @Graph seems like it may be an obstacle for large graphs.

**Comment by Incarnation-p-lee** [comment]
@corneil 
Thanks for trying this repo. We add `@Graph` here for `Network` for this scenario, like prepare the `Network` instance with `EdgeList` and `VertexList`, and you can use `repository.save(network)` to insert the whole graph at one time, instead of save the `EdgeList` and `VertexList` many times.

We would like to provide another way for create `Graph` in database here. Or Do U have some advice about this ? Thanks in advance!

**Comment by corneil** [comment]
If I try to save a list of edges or vertices all objects should be saved that are discovered. Maybe a built-in Graph class can be provided to help with constraining the objects I want to load. How about a base class that can be extended to provided access to underlying edges and vertices in conjunction with gremlin API

**Comment by Incarnation-p-lee** [comment]
If there is one base class for providing these mess, there may be some effect for configuration on `repository`, `template` for instance. And there is another usage, like class `Network`, we can create 2 instance of this class, representing 2 sub-graph in database.

**Comment by corneil** [comment]
My idea is that the base is optional. I extend it when declaring one or more of my entities making it easier to use it in conjunction with the Gremlin API.

**Comment by Incarnation-p-lee** [comment]
you mean that you still want to do some operation like `insert` from the inherited class, right ? Could you please provide some sample code ? I am not sure understand correctly or not.

**Comment by corneil** [comment]
```java
@Data
class Person extends AbstractVertex {
    @Id
    private String id;
    private String name;
    private Gender gender;
}

@AutoWire
PersonRepository personRepository;
@AutoWire
// Gremlin Graph
Graph graph;
Person person = personRepository.findByName("someName");
List<Person> friends = GremlinUtils.mapToList(person.vertices("FRIENDS"), Person.class);
//OR 
List<Person> friends = personRepository.findAll(person.vertices("FRIENDS"));
// OR
List<Person> maleFriends = personRepostory.findAll(graph.traversal().V(person).out("FRIENDS").has("gender", Gender.MALE).select());
```

`person` can also be used in the traversal API since it is a Vertex, I can't think of a nice example at the moment.
I can see the use for doing a complex traversal and mapping the result to entities. Either by have a findAll that can work with GraphTraversal or A helper function to map the traversal to an entity

**Comment by corneil** [comment]
Another benefit of using a base class for Vertex and Edge is that other code that can navigate a graph for visualization will work with the entities that extend AbstractVertex and AbstractEdge.

**Comment by Incarnation-p-lee** [comment]
@corneil 
Thanks for your explain. You can send one PR or PR list for that.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
