### ISSUE TITLE
Is GremlinTemplate planned?

### ISSUE THREAD

**Issue by corneil** [microsoft/spring-data-gremlin#122]
Most of the Spring Data projects have a template class that allows closer access to the underlying technology.
GremlinTemplate should provide access to the underlying Graph and traversal API.

**Comment by corneil** [comment]
I can see the need for using normal gremlin API to do traversal and then load an object graph. This means somehow specifying the limits of the load process.

**Comment by Incarnation-p-lee** [comment]
@corneil 
Make sense, we will plan to add that feature in short future.

**Comment by jxcypress** [comment]
Hi,I start the gremlin server ,then config the application.yml  in maven project like this,is it right ??:
gremlin:
  endpoint: 127.0.0.1
  username: admin
  password: admin
  port: 8182
  telemetryAllowed: false

**Comment by Incarnation-p-lee** [comment]
@jxcypress 
this may based on your configuration from gremlin server, you can ref the configuration from [.travis.yml](https://github.com/Microsoft/spring-data-gremlin/blob/master/.travis.yml)

**Comment by jxcypress** [comment]
Hi,I use orientdb with embedded gremlin server for test,the version is 'orientdb-tp3-3.0.10.tar.gz',but I get an error when using spring-data-gremlin ,here is the config file and the maven project error log,thank you for your help!
[gremlin-server.yaml.txt](https://github.com/Microsoft/spring-data-gremlin/files/2524887/gremlin-server.yaml.txt)
[demodb.properties.txt](https://github.com/Microsoft/spring-data-gremlin/files/2524889/demodb.properties.txt)
[log.txt](https://github.com/Microsoft/spring-data-gremlin/files/2524890/log.txt)

**Comment by Incarnation-p-lee** [comment]
@jxcypress 
I take a look into you log, but I am not very familiar with orientDB. So I just scan the config from gremlin side, the endpoint in gremlinserver is localhost, suggest to align this with application.yml.
Another way of testing orientDB link is try to collect it with gremlin-client.
About the serializer, current we use `- { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0, config: { serializeResultToString: true }}`, we will make it configurable later.

**Comment by rajanpupa** [comment]
Is there any update on this? If not Template, is there anything with which I can traverse through the graph relations and get the Vertexes?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
