### ISSUE TITLE
Collection annotation

### ISSUE THREAD

**Issue by corneil** [microsoft/spring-data-gremlin#123]
I can see the need for annotating a collection of vertex to indicate the edges involved. There are cases when you have edges that don't have attributes and you don't need a separate entity class to represent that edge. A lot like @ManyToMany in JPA.

**Comment by Incarnation-p-lee** [comment]
@corneil 
Thanks for you issues, As limited resource and too many feature list. Any PR is welcome.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
