### ISSUE TITLE
Transactional support?

### ISSUE THREAD

**Issue by thinh76** [microsoft/spring-data-gremlin#130]
Is there a way to handle transactions like the old JDBC fashion way? 
`this.networkRepo.save(this.network);` what happens if some vertexes were successfully saved and some were not. How can we roll it back?

**Comment by Incarnation-p-lee** [comment]
@thinh76 
Thanks for your issues, for now transactional like `@Transactional` is not supported yet, We can add it to our new feature plan. Or any contribution PR is welcome.

**Comment by mingjinc** [comment]
@Incarnation-p-lee based on @Transactional is not supported,  if our application wonder to add transaction now. Any other option/work around for transaction?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
