### ISSUE TITLE
Why does @Id fields have to be String?

### ISSUE THREAD

**Issue by kschulst** [Microsoft/spring-data-gremlin#131]
I'm experimenting spring-data-gremlin, using the tinkerpop gremlin-server as backend. I am playing with the "modern graph" supplied by the gremlin-server, which out of the box the graph has integer type IDs.

![image](https://user-images.githubusercontent.com/21902/43507392-48ce65fa-956d-11e8-84f0-ff07ea73ae23.png)

However, spring-data-gremlin enforces `@Id`-annotated fields to be `String`:
https://github.com/Microsoft/spring-data-gremlin/blob/456264b22f527b8ac62a378d8076f36a818ea234/src/main/java/com/microsoft/spring/data/gremlin/common/GremlinUtils.java#L63-L65

What is the reason for only allowing String? It seems that gremlin-server, when running in a default and naïve configuration, non-String IDs are being used.

If I save one of my vertice to the graph, using something like:
```
personRepository.save(Person.builder().id("123").name("joe").build()));
```
...I end up with a vertex in the graph with a generated id (e.g. 17), and "id" as a property, like so:
```
gremlin> :> g.V(17).properties()
==>vp[name->joe]
==>vp[id->123]
```

**Comment by Incarnation-p-lee** [comment]
@kschulst 
Thanks for your issue and try `spring-data-gremlin`. As the first version of this repo, we pick the simplest one(`String`) for `@Id`. Actually we can add more type for `@Id`, but in fact we also need to convert it to `String` and store it database. Some graph database may require String type for ID, or you may got some error like below:
```
Gremlin Query Execution Error: Add Table Reference: Construct Node: Vertex's ID must be a string Source
```

For generated Id, I think the id should be unique in database, id and label is not the part of properties. Gremlin console may support both number and string for id. See following:
```gremlin
gremlin> g.addV().property(id, 123).property('name', 'name0')
==>v[123]
gremlin> g.addV().property(id, '123').property('name', 'name1')
==>v[123]
gremlin> g.V()
==>v[123]
==>v[123]
gremlin> g.V().valueMap()
==>[name:[name1]]
==>[name:[name0]]
gremlin> g.V().properties()
==>vp[name->name1]
==>vp[name->name0]
gremlin> g.V(123)
==>v[123]
gremlin> g.V('123')
==>v[123]
gremlin> g.V(123).valueMap()
==>[name:[name0]]
gremlin> g.V('123').valueMap()
==>[name:[name1]]
```

**Comment by kschulst** [comment]
Thanks a lot for the quick response! Sounds reasonable to start with String....

I guess that I was also a bit confused by the different serializers that are being used. My gremlin server configuration used the `GryoMessageSerializerV3d0` serializer, but after digging a bit it seems that spring-data-gremlin only supports the `GryoMessageSerializerV1d0` serializer. Is this the case?

Anyway, having configured my server to use `GryoMessageSerializerV1d0`, things work much more smoothly.

**However, I have a follow-up question...**

As noted earlier, When I do
```
personRepository.save(Person.builder().id("123").name("joe").build()));
```
...I end up with a vertex in the graph with a generated id (e.g. 17), and "id" as a property, like so:
```
gremlin> :> g.V(17).properties()
==>vp[name->joe]
==>vp[id->123]
```
To do the same "save-action" in the gremlin console you would do something like:
```
gremlin> :> g.addV().property(id, '123').property('name', 'name1')
```
(note that the `id` property is not surrounded by apostrophes)

If I do the same, but WITH surrounding apostrophes on the id property:
```
gremlin> :> g.addV().property('id', '123').property('name', 'name1')
```
... I end up with the same result as the `personRepository.save(...)`.

I looked into `com.microsoft.spring.data.gremlin.conversion.script.GremlinScriptLiteralVertex `:
```
    public List<String> generateUpdateScript(@NonNull GremlinSource source) {
        if (!(source instanceof GremlinSourceVertex)) {
            throw new GremlinUnexpectedSourceTypeException("should be the instance of GremlinSourceVertex");
        }

        final List<String> scriptList = new ArrayList<>();
        final String id = source.getId();
        final Map<String, Object> properties = source.getProperties();

        Assert.notNull(id, "id should not be null");
        Assert.notNull(properties, "properties should not be null");

        scriptList.add(Constants.GREMLIN_PRIMITIVE_GRAPH);
        scriptList.add(String.format(Constants.GREMLIN_PRIMITIVE_VERTEX, id));

        scriptList.addAll(generateProperties(properties));

        final String query = String.join(Constants.GREMLIN_PRIMITIVE_INVOKE, scriptList);

        return Collections.singletonList(query);
    }
```
The `generateProperties(properties)` ends up in a `generateProperty` method that uses the following template for the id field:
```
    public static final String GREMLIN_PRIMITIVE_PROPERTY_STRING = "property('%s', '%s')";
```
...which in effect will generate the id as a property WITH surrounding apostrophes. Is this a bug? Or is it something wrong with my configuration?

**Comment by kschulst** [comment]
A related issue, I see the same kind of behaviour for:
```
gremlin> :> g.V().has(label, 'Person')
==>v[17]
==>v[22]
==>v[13]
```
vs 
```
gremlin> :> g.V().has('label', 'Person')
gremlin> (nothing found)
```
spring-data-gremlin uses the following template:
```
    public static final String GREMLIN_PRIMITIVE_HAS_STRING = "has('%s', '%s')";
```
e.g.
```
    @Override
    public List<String> generateFindAllScript(@NonNull GremlinSource source) {
        final String label = source.getLabel();
        final List<String> scriptList = new ArrayList<>();

        Assert.notNull(label, "label should not be null");

        scriptList.add(Constants.GREMLIN_PRIMITIVE_GRAPH);
        scriptList.add(Constants.GREMLIN_PRIMITIVE_VERTEX_ALL);
        scriptList.add(String.format(Constants.GREMLIN_PRIMITIVE_HAS_STRING, Constants.PROPERTY_LABEL, label));

        final String query = String.join(Constants.GREMLIN_PRIMITIVE_INVOKE, scriptList);

        return Collections.singletonList(query);
    }
```

This has to be something with by configuration, right?

**Comment by Incarnation-p-lee** [comment]
@kschulst 
Yes, we use default result serializer(`GraphSONMessageSerializerV1d0`) in gremlin driver, and I think we can make it configurable in short future.

For `id` and `'id'`, as I mentioned, gremlin keep 2 reserved property `id` and `label`, and treat `id` and `'id'` the same thing in database. Base on that, our implementation just use `property('%s', '%s')` for all properties include `id` and `label`. Either use `id` or `'id'` in generated query, we got the same data in database. So `('%s', '%s')` is good enough for query.

I did some query literal on `azure cosmosdb with graph API`, the `'id'` and `id`(also for label) works well.

```gremlin
g.addV('person').property(id, '1').property('name', 'name0')
g.addV('person').property(id, '1').property('name', 'name0')
g.V()
[
  {
    "id": "123",
    "label": "panli",
    "type": "vertex"
  },
  {
    "id": "1",
    "label": "person",
    "type": "vertex",
    "properties": {
      "name": [
        {
          "id": "17e89cad-d704-449a-a76c-2a856350a7e6",
          "value": "name0"
        }
      ]
    }
  },
  {
    "id": "2",
    "label": "person",
    "type": "vertex",
    "properties": {
      "name": [
        {
          "id": "4913264b-7d69-43fe-838f-7fb80303ebe8",
          "value": "name2"
        }
      ]
    }
  }
]

g.V().has('label', 'person')

[
  {
    "id": "1",
    "label": "person",
    "type": "vertex",
    "properties": {
      "name": [
        {
          "id": "17e89cad-d704-449a-a76c-2a856350a7e6",
          "value": "name0"
        }
      ]
    }
  },
  {
    "id": "2",
    "label": "person",
    "type": "vertex",
    "properties": {
      "name": [
        {
          "id": "4913264b-7d69-43fe-838f-7fb80303ebe8",
          "value": "name2"
        }
      ]
    }
  }
]

g.V().has(label, 'person')

[
  {
    "id": "1",
    "label": "person",
    "type": "vertex",
    "properties": {
      "name": [
        {
          "id": "17e89cad-d704-449a-a76c-2a856350a7e6",
          "value": "name0"
        }
      ]
    }
  },
  {
    "id": "2",
    "label": "person",
    "type": "vertex",
    "properties": {
      "name": [
        {
          "id": "4913264b-7d69-43fe-838f-7fb80303ebe8",
          "value": "name2"
        }
      ]
    }
  }
]
```

**Comment by kschulst** [comment]
We're not using `azure cosmosdb`. Right now I've only tested `gremlin-server`, but we're aiming to use `aws neptune` (I'm gonna see how this works with neptune later today).

Anyway, spring-data-gremlin should work with all gremlin-compliant databases, such as `gremlin-server`. Might it be that the reason this works in `azure cosmosdb` is that it is more "forgiving"?

I could create a PR that fixes this issue, if you're interested?

**Comment by kschulst** [comment]
I am creating a separate issue (#132) for this, since the initial question has mutated a bit. Moving the discussion to that issue and closing this one.
