### ISSUE TITLE
Reserved property keywords (id, label) require special treatment

### ISSUE THREAD

**Issue by kschulst** [Microsoft/spring-data-gremlin#132]
(Refer to #131 for a more detailed discussion about this)

`spring-data-gremlin` surrounds reserved property keywords such as `id` and `label` with apostrophes. This results in `id` and `label` to be treated as standard properties.

I have tested this on both `gremlin-server` and `aws neptune` - with the same result.

Here's an excerpt from my gremlin console when accessing `aws neptune`:
```
gremlin> g.addV('Person').property('id', '1').property('name', 'name1')
==>v[aeb27ce1-087a-978c-0eaa-91adb705c355]
gremlin> g.addV('Person').property(id, '2').property('name', 'name2')
==>v[2]
gremlin> g.addV('Person').property(T.id, '3').property('name', 'name3')
==>v[3]

gremlin> g.V('aeb27ce1-087a-978c-0eaa-91adb705c355').properties()
==>vp[id->1]
==>vp[name->name1]
gremlin> g.V('2').properties()
==>vp[name->name2]

gremlin> g.V().has('label', 'Person')
gremlin> g.V().has(label, 'Person')
==>v[2]
==>v[aeb27ce1-087a-978c-0eaa-91adb705c355]
==>v[3]
```

This issue could be solved by making reserved keywords such as `label` and `id` use other templates than today:
```
public static final String GREMLIN_PRIMITIVE_PROPERTY_STRING = "property('%s', '%s')
public static final String GREMLIN_PRIMITIVE_HAS_STRING = "property('%s', '%s')
```

Would you be interested if I created a PR to solve this issue?

**Comment by kschulst** [comment]
@Incarnation-p-lee: As you pointed out in #131, you don't see the same behaviour for `azure cosmosdb`. Might it be that the reason this works in azure cosmosdb is that it is more "forgiving"?

Judging by the name, `spring-data-gremlin` should work with all gremlin compliant databases, such as `gremlin-server`, `aws neptune` and others, not only `azure cosmosdb`.

**Comment by kschulst** [comment]
I was prevented (access denied) from pushing my branch to your repo to create a PR, so I've proposed a PR from my fork instead - see #133.

Let me know if you prefer it any other way.

**Comment by Incarnation-p-lee** [comment]
@kschulst 
Thanks for your effect. Have you received the link of inviting ? Or could you please share your email ?

**Comment by kschulst** [comment]
Right, I had overlooked the invite mail. I have created a new PR from a branch instead of fork now. See #134
