### ISSUE TITLE
Update Maven to current Master 2.0.1-SNAPSHOT?

### ISSUE THREAD

**Issue by TeVexo** [Microsoft/spring-data-gremlin#148]
Is it possible to upgrade the maven repository to the current master? 
Got Issues using the 2.0.0 Version that are fixed in the current version of the master. (Issue #134)

**Comment by Incarnation-p-lee** [comment]
we will plan to release new version after the id/label issue, will info you then.

**Comment by Incarnation-p-lee** [comment]
@TeVexo 
Close this issue as releaed.
