### ISSUE TITLE
How do create custom query use annotation 'Query' like neo4j style?

### ISSUE THREAD

**Issue by w279805299** [microsoft/spring-data-gremlin#159]
as title。

use neo4j  dependency.
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-neo4j</artifactId>
</dependency>

I can write custom query like this:
@Query("match(n:Movie) where n.title={title} return n.rating")
Double getMovieRating(@Param("title") String title);

Does spring-data-gremlin can ?

**Comment by Incarnation-p-lee** [comment]
@w279805299 
Thanks for interesting spring-data-gremlin. For now, this feature is not supported, we will add it to our feature plan. Or you can also send the PR for this.

**Comment by anthony-o** [comment]
Perhaps that some code from https://github.com/zifnab87/spring-data-gremlin could be copied / adapted to answer this feature and many others?

**Comment by Incarnation-p-lee** [comment]
@anthony-o 
Thanks for your information, we may take a look and evaluate the effect of this feature.

**Comment by frne** [comment]
@Incarnation-p-lee Any news on this one? Custom Gremlin queries would be a crucial feature for us.

**Comment by Incarnation-p-lee** [comment]
@frne 
Thanks, we are working on this.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
