### ISSUE TITLE
add support for Spring-boot 2.1.0

### ISSUE THREAD

**Issue by GillesBodart** [Microsoft/spring-data-gremlin#188]
The repository mechanism is broken when you take spring boot 2.1.0 as a parent.

`You have defined query method in the repository but you don't have any query lookup strategy defined. The infrastructure apparently does not support query methods!`

If I downgrade to Spring-boot 2.0.6.REALEASE it's ok

**Comment by Incarnation-p-lee** [comment]
@GillesBodart 
Thanks for trying spring-data-gremlin, for now query method feature is not finished for all keywords, as well as lookup strategy. We may add this support in short future. Also you can contribution code.

**Comment by Incarnation-p-lee** [comment]
close this as 2.1.x released already.
