### ISSUE TITLE
Gremlin-server 3.4.0 enabled ReferenceElementStrategy.

### ISSUE THREAD

**Issue by Incarnation-p-lee** [microsoft/spring-data-gremlin#201]
* This feature removes properties and only include the id and label.
* Breaking change and we need to adjust our code for this.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
