### ISSUE TITLE
Connecting to Multiple Database Instances

### ISSUE THREAD

**Issue by kai18** [microsoft/spring-data-gremlin#204]
Is it possible to connect to multiple (at least 2) database instances through this API. Both are Cosmos DB but have different configuration.

If not, can we please open a feature request for it?

**Comment by Incarnation-p-lee** [comment]
@kai18 
thanks for that. For now only one database is supported from this repo. You can file one issue for this.

**Comment by nuclearfungus** [comment]
did anyone find an alternative to achieve this?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
