### ISSUE TITLE
Save Property containing a list as Gremlin list not as string

### ISSUE THREAD

**Issue by TeVexo** [microsoft/spring-data-gremlin#221]
## Expected Behavior
Save the Java list object as Gremlin list to enable the possibility to unfold the list via Gremlin traversal.

## Current Behavior
The Java list object is saved as String.

## Possible Solution
Add the following to the com/microsoft/spring/data/gremlin/common/Constants.java file:

```java
public static final String GREMLIN_PRIMITIVE_PROPERTY_LIST = "property('%s', [%s])";
```

Add something like the following to the com/microsoft/spring/data/gremlin/conversion/script/AbstractGremlinScriptLiteral.java file:

```java
private static String generateProperty(@NonNull String name, @NonNull List<String> value) {
    return String.format(GREMLIN_PRIMITIVE_PROPERTY_LIST, name, value.toString());
}
```

**Comment by Incarnation-p-lee** [comment]
@TeVexo
Thanks for issue this. You mean if you got one collection field for instance, you would like to flat map to some properties, right ? 
For example, List<Person> persons = Arrays.asList(p1, p2);, you would like to see two properties of these two Person.

**Comment by TeVexo** [comment]
@Incarnation-p-lee 
In Gremlin you can define a property with the value as list (> .property( 'list', [1,2,3] <). Then it is possible to acces single values contained in the list of the property by unfolding it. 

In the query language you can use something like the following to check if there is one or more vertices with the property "list" containing 1:
```
g.V().has('list', unfold().is(1))
``` 

Your suggestion could also be used to handle lists by "overloading" a property key with more than one value. Then you could directly access the fitting vertices by using the following:

``` 
g.V().has('list', 1)
```
This could be more complicated to map and is slightly different to wrap your head araund as plain java developer in my opinion but also a good solution.

**Comment by Incarnation-p-lee** [comment]
@TeVexo 
Thanks for information. So it looks the gremlin server provide fold/unfolder which maybe more native I think. As this may be minor feature, Can you file one PR for this ? Thanks in advance!

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
