### ISSUE TITLE
GremlinConfig telemeryAllowed hard coded 

### ISSUE THREAD

**Issue by ardochoke** [Microsoft/spring-data-gremlin#222]
In GremlinConfig.builder(....)   the .telemetryAllowed parameter is hard coded to true in the builder. Should this be set to the private boolean telemetryAllowed variable so that it picks up the configuration correctly?

The question may be better worded as: is there a reason that when I turn this setting off, why does the application still attempt to reach rt.services.visualstudio.com:443?

**Comment by ardochoke** [comment]
I upgraded to latest version and this issue seems resolved now. I also found that I could add the following to force disable at a lower level:
azure:
    application-insights:
        enabled: false
        web:
            enabled: false

Apologies for the noise in the issues list, I should have tried a few more things before posting...

**Comment by Incarnation-p-lee** [comment]
Thanks a lot. No problem. We have fix that already, any other question please feel free to contact us.
