### ISSUE TITLE
Query findAllByFieldName is not working

### ISSUE THREAD

**Issue by apetropavlovskiy** [microsoft/spring-data-gremlin#224]
## Expected Behavior
```java
Iterable<SomeModel> findAllByFieldName(Iterable<String> values);
```
Should generate:
```g.V().has('someLabel', 'fieldName', within('v1', 'v2', 'v3' ...))```
or
```g.V().has(label, 'someLabel').has('fieldName', within('v1', 'v2', 'v3' ...))```

## Current Behavior
No query is generating at all. No exceptions.

**Comment by rekon** [comment]
Hi, I think it is an enhancement that's yet to be done. [Project:TODO](https://github.com/microsoft/spring-data-gremlin/projects/1#card-12207087). Please feel free to make a PR for the enhancement

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
