### ISSUE TITLE
[Question] is it possible to work with cosmosDB partitions

### ISSUE THREAD

**Issue by softwaremagico** [microsoft/spring-data-gremlin#226]
If exists a CosmosDB with [partitions](https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview), is it possible to use spring-data-gremlin with it?

At least, I am not able to find where to put the partition key when working with a GremlinRepository.

**Comment by Incarnation-p-lee** [comment]
@softwaremagico Thanks for you issue, this repo is focus on gremlin itself and Partition is something cosmosdb special. So that may out of the scope here.

**Comment by softwaremagico** [comment]
Ok, thanks for your response.

**Comment by softwaremagico** [comment]
After some checks, basically if I add the property "partition" to a vertex, cosmosDB handle correctly and put it in the correct partition. Nothing else special needed.
