### ISSUE TITLE
Search relationship by from vertex assumes a label of the relationship that can be incorrect. 

### ISSUE THREAD

**Issue by softwaremagico** [microsoft/spring-data-gremlin#227]
I have a simple relation with the typical `@EdgeFrom` and `@EdgeTo` annotations:

```
@Edge
public class Relationship {

        @Id
	private String id;

        private String label;

	@EdgeFrom
	private Vertex from;

	@EdgeTo
	private Vertex to;

        ...
}
```

And I create a simple gremlinrepositoy with one extra method as follows:

```
@Repository
public interface RelationshipRepository extends GremlinRepository<Relationship, String> {

	public List<Relationship> findByFrom(Vertex from);

}
```

The problem I have is: when translated to a gremlin query, is adding some checks to the label of the relationship assuming that the label is the class name. As it is possible to change the label name, the query does not work any more. 

## Expected Behavior
 g.E().where(has('from', '{"id":"fromId","name":"fromName", ...}'))

## Current Behavior
 g.E()**.has(label, 'Relationship')**.where(has('from', '{"id":"fromId","name":"fromName", ...}'))

Here the search is assuming always that the label is "Relationship", but can be different. 

## Possible Solution
I am not sure why is the reason to include the label check (performance?), but as the label can be set at any relationship entity, this check is invalid and producing empty search. Probably must be removed. 

## Your Environment
* Version used: 2.1.2
* Operating System and version (desktop or mobile): Ubuntu 18.04.2 LTS

**Comment by softwaremagico** [comment]
Ok, seems that the issue is related to the idea as annotation `@Edge(label="")` and property of a Relationship `label` is translated to the same property in CosmosDB. If editing the label using the annotation seems that is working fine, but if change as a property of a class, seems not. 

The original code of `GremlinEntityInformation` in the function `createGremlinSource` seems that is assigning the domainName as a label if the annotation label is empty. And this is the reason why does not match the label set as property of the class. 

Obviously for now I will remove the property of the class and only use the annotation. I cannot have autogenerated labels but is not a big problem.

**Comment by Incarnation-p-lee** [comment]
@softwaremagico 
Great! The default label take the domainName as it may has some benefits when there are some complicated query later. Please feel free to contact us if there is other issues.

**Comment by Incarnation-p-lee** [comment]
Close this for now, please feel free to reopen it if similar issue occurs.
