### ISSUE TITLE
How to connect to neo4j using spring data gremlin if it doesn't provide bolt/https protocol options

### ISSUE THREAD

**Issue by RaghavMundhada** [microsoft/spring-data-gremlin#229]
Is there any way to connect with neo4j without using bolt/https protocols? This is the sample project I have created [https://github.com/RaghavMundhada/gremlin-neo4j-connection] . On Running this I am getting the following error
"Caused by: java.util.concurrent.TimeoutException: Timed out while waiting for an available host - check the client configuration and connectivity to the server if this message persists"

My yaml file looks like this:
gremlin:
  endpoint: localhost
  port: 7687
  username: /dbs/neo4j/colls/neo4j
  password: raghav123
  sslEnabled: false
  telemetryAllowed: true

Can you tell me how can i fix this?

**Comment by Incarnation-p-lee** [comment]
I think it may need gremlin java sdk support. As below dependency, we need to investigate is the connection to gremlin server configurable or not.
```
        <dependency>
            <groupId>org.apache.tinkerpop</groupId>
            <artifactId>gremlin-driver</artifactId>
            <version>${org.apache.tinkerpop.gremlin.driver.version}</version>
        </dependency>
```

**Comment by SsebaddukaG** [comment]
Hello,
Any updates on the above query?

Thank you

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
