### ISSUE TITLE
[Documentation] Cosmosdb PartitionKey not supported

### ISSUE THREAD

**Issue by gmousset** [microsoft/spring-data-gremlin#232]
Please could you write clearly that this library is not fully compatible with Microsoft Azure Cosmosdb, especially for partition key which is an important feature. 
Users could naively expect that a microsoft lib supports a microsoft product as explained in README : 

> "This project works with any Gremlin-compatible data store, and also with Azure Cosmos DB"

Thanks

**Comment by Incarnation-p-lee** [comment]
I think you may mix the concept of gremlin and backend graph. As READ.ME indicates, spring-data-gremlin is one generic project for gremlin independent to backend graph db. So the Cosmosdb graph API, neo4j special feature is out of the scope of this project. But for gremlin part of these backend db, this project should be fully support.

**Comment by gmousset** [comment]
I agree with you, spring-data-gremlin is fully compatible with gremlin. 
In the case of CosmosDB, Microsoft introduced the partition key feature which is **mandatory** for the user if you expect to store more than 10 GB.
Maybe the true problem is CosmosDB is not fully compatible with generic gremlin api.
It could be nice to add a warning in the documentation, or remove cosmosdb if it.

**Comment by saragluna** [comment]
I agree with you that the true problem is CosmosDB is not fully compatible with generic gremlin api.
`partition key` is a special feature of CosmosDB and this project works with any Gremlin-compatible data store.

**Comment by slashphi** [comment]
Is there any libarary which fully supports CosmosDB. Otherwise I could offer to have a PR to support also PartitionKeys

**Comment by wavermartijn** [comment]
Is there any chance this will be add soon? It's really confusing as the compatability with CosmosDB for this library is mentioned here specifically:
https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-gremlin-java-app-with-cosmos-db

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
