### ISSUE TITLE
Is anyone working on this Project?

### ISSUE THREAD

**Issue by arabbani** [microsoft/spring-data-gremlin#241]
There are no recent commits on this repo. Is anyone maintaining the project. I want to use it for production. Can I use it safely with future support.

**Comment by saragluna** [comment]
Thanks for reaching out. Yes, this project is under our maintenance though there're no recent commits.

**Comment by arabbani** [comment]
Ok thans

**Comment by arabbani** [comment]
Is it published on gradle?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
