### ISSUE TITLE
any chance to merge capabilities from this fork of gjrwebber implementation? 

### ISSUE THREAD

**Issue by zifnab87** [microsoft/spring-data-gremlin#242]
Hi it is been a while since there was an independent (almost dead though) attempt to implement a lot of functionalities similar to the ones you are implementing/open sourcing - I tried to migrate the abandoned fork https://github.com/gjrwebber/spring-data-gremlin to use TP3 and fix most of the tests but I couldn't continue alone- https://github.com/zifnab87/spring-data-gremlin. I am curious if some of the work could be integrated with your repository so it becomes a mature spring-data project at some point

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
