### ISSUE TITLE
Support Edge Label Multiplicity

### ISSUE THREAD

**Issue by Tin-Nguyen** [microsoft/spring-data-gremlin#244]
Hi all,

I'm looking for How to setup Edge Label Multiplicity via `spring-data-gremlin`, anyone knows the feature has been developed in this library or not yet?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
