### ISSUE TITLE
timeout exception occurs when trying to import a graph 

### ISSUE THREAD

**Issue by tschn** [microsoft/spring-data-gremlin#247]
**Your issue may already be reported! Please search before creating a new one.**

## Expected Behavior
* When importing a graph using spring-data-gremlin-boot-starter, the import should complete without issues

## Current Behavior
* import fails with java.util.concurrent.TimeoutException: null

## Possible Solution
* timeout settings for gremlin driver?

## Steps to Reproduce (for bugs)
* step-1
* step-2
* ...

## Snapshot Code for Reproduce 
```java

        Map<String, Raptas> raptasMap = new HashMap<>();
        raptas.stream().forEach((Raptas rapta) -> {
            raptasMap.put(rapta.getRaptaId(), rapta);
        });

        List<RaptaRapta> edges = new ArrayList<>();
        raptas.stream().forEach((Raptas rapta) -> {
                    if (raptasMap.get(rapta.getRefRaptaId()) != null) {
                        edges.add(new RaptaRapta(rapta.getRaptaId() + "_" + rapta.getRefRaptaId(), rapta, raptasMap.get(rapta.getRefRaptaId())));
                    }
                }
        );

        this.network.getEdges().addAll(edges);
        this.network.getVertexes().addAll(raptas);
        this.networkRepository.save(this.network);
```

## Branch
* 2.1.7

## Your Environment
* Version used:
* Operating System and version (desktop or mobile): Ubuntu
* SDK version:<azure.version>2.1.7</azure.version>
		<dependency>
			<groupId>org.apache.tinkerpop</groupId>
			<artifactId>gremlin-driver</artifactId>
			<version>3.2.11</version>
		</dependency>

**Comment by neuqlz** [comment]
Thanks for your feedback, we will inspect it and give you a response later.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
