### ISSUE TITLE
Support @Query annotation for executing Custom Queries

### ISSUE THREAD

**Issue by Tin-Nguyen** [microsoft/spring-data-gremlin#248]
## Expected Behavior
```java
@Repository
public interface TodoRepository extends GremlinRepository<ToDo, String> {
 
    @Query("g.V().has(label, 'TODO').has(id, :id)") 
    String findTitleById(@Param("id") Long id);
}
```

## Current Behavior
* Not support @Query

## Possible Solution
* I might create a PR soon

## Steps to Reproduce (for bugs)
* Not a bug, this is a suggestion

## Your Environment
* Version used:
* Operating System and version (desktop or mobile):
* SDK version:

**Comment by neuqlz** [comment]
thanks for your feedback, we will inspect it and give you a response later.

**Comment by gguttikonda** [comment]
fyi: We attempted implementing this and here is the PR https://github.com/microsoft/spring-data-gremlin/pull/255

**Comment by Prajyot1712** [comment]
@gguttikonda when will this be available to be used?

**Comment by gguttikonda** [comment]
A PR(https://github.com/microsoft/spring-data-gremlin/pull/255) is already
created for this and it's currently waiting to be reviewed and merged.

- Ganesh

**Comment by slashphi** [comment]
@neuqlz is there a plan to accept the PR?

**Comment by badalrocks** [comment]
Can this PR be merged?

**Comment by MariaLapovska** [comment]
Hi guys, this feature would be very useful, are you planning on releasing it? Since the code is already there

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
