### ISSUE TITLE
Is anyone able to get this project work with gremlin server with OrientDB graphs. 

### ISSUE THREAD

**Issue by rajatjain1996** [microsoft/spring-data-gremlin#262]
**Your issue may already be reported! Please search before creating a new one.**

## Expected Behavior
* placeholder

## Current Behavior
* placeholder

## Possible Solution
* placeholder

## Steps to Reproduce (for bugs)
* step-1
* step-2
* ...

## Snapshot Code for Reproduce 
```java
@SpringBootApplication
public class Application {
    public static void main(String... args) {
        SpringApplication.run(Application.class, args);
    }
}
```

## Branch
* placeholder

## Your Environment
* Version used:
* Operating System and version (desktop or mobile):
* SDK version:

**Comment by rajatjain1996** [comment]
I am getting following error with example code
Caused by: java.util.concurrent.ExecutionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: Vertex does not support user supplied identifier

**Comment by saragluna** [comment]
The same problem as #231, closing this issue.
