### ISSUE TITLE
Feature request: Access response headers

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/spring-data-gremlin#265]
**Your issue may already be reported! Please search before creating a new one.**

## Expected Behavior
* Able to access response headers (for instance, the Cosmos DB RU headers - https://docs.microsoft.com/en-us/azure/cosmos-db/gremlin-headers#headers)

## Current Behavior
* Unable to access (I think? It's not documented)

## Possible Solution
* Potentially handle this like the Cosmos SQL API Spring connector?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
