### ISSUE TITLE
about Transactional support

### ISSUE THREAD

**Issue by jiangjunlong** [microsoft/spring-data-gremlin#267]
based on @transactional is not supported, if our application wonder to add transaction now. Any other option/work around for transaction? 
Seeing that the code is still released, but there is no release note and no code submission, is it still maintained?

**Comment by saragluna** [comment]
Sorry for the late response. Yes, it's still maintained but due to our limited resources now, we need to evaluate new feature requests.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
