### ISSUE TITLE
Unsupported Error: Gremlin op does not support by(traversal)

### ISSUE THREAD

**Issue by gautamdivgi** [microsoft/spring-data-gremlin#268]
I'm trying to run this query
g.V().limit(100).dedup().as('node').project('id', 'label', 'properties', 'edges').by(__.id()).by(__.label()).by(__.valueMap().by(__.unfold())).by(__.outE().project('id', 'from', 'to', 'label', 'properties').by(__.id()).by(__.select('node').id()).by(__.inV().id()).by(__.label()).by(__.valueMap().by(__.unfold())).fold())

When running it I get this error
ActivityId : 36e58a6f-b6d9-49e3-96b7-96a42ce7821e
ExceptionType : GraphNotSupportedException
ExceptionMessage :
	Unsupported Error: Gremlin op does not support by(traversal)
Source : Microsoft.Azure.Cosmos.Gremlin.Core
	GremlinRequestId : 36e58a6f-b6d9-49e3-96b7-96a42ce7821e
	Context : graphcompute
	Scope : graphcmd-invoke
	GraphInterOpStatusCode : NotSupported
	HResult : 0x80131500

I'm using gremlinpython 3.4.6.

The docs seems to indicate that "by" is supported --> https://docs.microsoft.com/en-us/azure/cosmos-db/gremlin-compatibility.

Any guidance would be appreciated as to why this doesn't work.

**Comment by lu-cheng** [comment]
Have you used the spring-data-gremlin project?

**Comment by gautamdivgi** [comment]
ack - no. apologies. this happened when using the python libraries. I think the bytecode traversal is a limitation for CosmosDB. I'm closing this.
