### ISSUE TITLE
When I add vertex,an exception is thrown(java.lang.IllegalArgumentException: should contain id property),but the id is automatically generated with annotations

### ISSUE THREAD

**Issue by huangjj96** [microsoft/spring-data-gremlin#271]
![image](https://user-images.githubusercontent.com/70936420/92679303-a50e3780-f35a-11ea-90b3-7a0f0173a477.png)
![image](https://user-images.githubusercontent.com/70936420/92679322-b0616300-f35a-11ea-98c1-82f194caecb3.png)
![image](https://user-images.githubusercontent.com/70936420/92679329-b6574400-f35a-11ea-8533-cb018cd175fe.png)

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
