### ISSUE TITLE
Single quote is not escaped when saving/querying data

### ISSUE THREAD

**Issue by jurna** [microsoft/spring-data-gremlin#273]
When saving an entity wich has a property value with a single quote (for example "O'Niel"), you get an error:

```
com.microsoft.spring.data.gremlin.exception.GremlinQueryException: unable to complete query from gremlin; nested exception is java.util.concurrent.ExecutionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: startup failed:
Script84.groovy: 1: expecting ')', found 'Niel' @ line 1, column 117.
```

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
