### ISSUE TITLE
How can we create native Gremlin query?

### ISSUE THREAD

**Issue by senolatac** [microsoft/spring-data-gremlin#278]
## Expected Behavior
To create native gremlin query like:  `g.addV("Person").property("Name", "Justin").next();`

## Your Environment
* Version used: Spring boot 2.3.8, sprin-data-gremlin 2.3.0
* Operating System and version (desktop or mobile): Mac

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
