### ISSUE TITLE
Repository deleteAllByField not supported

### ISSUE THREAD

**Issue by AntonSynytsia** [microsoft/spring-data-gremlin#280]
I have vertices which contain `:viewId` property. I want to be able to delete all vertices by viewID property. Creating the following repository method an calling it did not work:
```java
void deleteAllByViewId(String viewId)
```

I had to revert to an approach of `node = findAllByViewId(viewId)` and `deleteAll(nodes)`, which is probably not efficient.

Request: add support for deleting all by field.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
