### ISSUE TITLE
Query method creation with keyword

### ISSUE THREAD

**Issue by Incarnation-p-lee** [microsoft/spring-data-gremlin#99]
New feature on Query Method Creation with Keyword. List the keyword and example in below.

* [x] AND
```java
List<T> findByNameAndCount(String name, int count);
```
* [x] OR
```java
List<T> findByNameOrCount(String name, int count);
```
* [x] Is_EQUALS
```java
List<T> findByName(String name);
```
* [x] AFTER
```java
List<T> findByCreateAtAfter(Date expireDate); // Only Date type is supported for now.
```
* [x] BEFORE
```java
List<T> findByCreateAtBefore(Date expiryDate); // Only Date type is supported for now.
```
* [ ] CONTAINING
* [x] BETWEEN
```java
List<T> findByCreateAtBetween(Date start, Date end);
```
* [ ] ENDING_WITH
* [x] EXISTS
```java
List<T> findByEnabledExists();
```
* [ ] FALSE
* [ ] GREATER_THAN
* [ ] GREATER_THAN_EQUALS
* [ ] IN
* [ ] IS
* [ ] IS_NOT_NULL
* [ ] IS_NULL
* [ ] LESS_THAN
* [ ] LESS_THAN_EQUAL
* [ ] LIKE
* [ ] NEAR
* [ ] NOT
* [ ] NOT_IN
* [ ] NOT_LIKE
* [ ] REGEX
* [ ] STARTING_WITH
* [ ] TRUE
* [ ] WITHIN

## Your Environment
* Operating System and version (desktop or mobile): 
* SDK version: 1.8+

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
